version: "2"
services:
  notebook:
    build: ./notebook-image
    image: notebook
    command: "jupyter-notebook"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ~/notebooks:/home/nb/notebooks
    tty: true
    user: nb
